const collections = [
    "alien.worlds",
    "funime.funko",
    "dungeonitems",
    "battleminers",
    "potter.funko",
    "galacticsaga",
    "realmnftgame",
    "thriveonmars",
    "outlawtroops",
    "castlesnftgo",
    "wbh.funko",
    "fools.funko",
    "squid.funko",
    "sjam.funko",
    "taco",
    "tng.funko",
    "tformr.funko",
    "twitchytides",
    "upliftium.hi",
    "dungeongolds",
    "plastk.funko",
    "skunkychunks",
    "waxapes",
    "skekofficial",
    "waxdeerjc",
    "hotwheels",
    "upliftworld",
    "godsglorynft",
    "apexconquest",
    "brixsocietyx"
  ];

  module.exports = collections;